## SmartBilling - application.properties

## App
app.frontend-url=http://localhost:4200
app.jwt.secret=7f3b9e2d1a6c8f4e0b5d7a9c2e4f6b8d1a3c5e7f9b2d4f6a8c0e2b4d6f8a1c3e
app.jwt.expiration-ms=86400000
app.jwt.refresh-expiration-ms=604800000

<<<<<<< HEAD
## Base de données PostgreSQL
=======
## Base de donnÃ©es PostgreSQL
>>>>>>> feature/Customer
spring.datasource.url=jdbc:postgresql://localhost:5432/smartbilling
spring.datasource.username=postgres
spring.datasource.password=ayette
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

## Email - Gmail SMTP
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ayetteboubaya@gmail.com
spring.mail.password=vobsmxahkcobngbu
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

## Serveur
<<<<<<< HEAD
server.port=8081

## Swagger UI ? http://localhost:8081/swagger-ui.html
=======
server.port=8082

## Swagger UI ? http://localhost:8082/swagger-ui.html
>>>>>>> feature/Customer
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.defaultModelsExpandDepth=1