# ??????????????????????????????????????????????????????????????
#  SmartBilling ? application.properties
# ??????????????????????????????????????????????????????????????

# ?? App ???????????????????????????????????????????????????????
app.frontend-url=http://localhost:4200
app.jwt.secret=CHANGEZ_CE_SECRET_PAR_UNE_CLE_DE_256_BITS_EN_PRODUCTION
app.jwt.expiration-ms=86400000

# ?? Base de données (adaptez selon votre config) ??????????????
spring.datasource.url=jdbc:postgresql://localhost:5432/smartbilling
spring.datasource.username=postgres
spring.datasource.password=ayette
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# ??????????????????????????????????????????????????????????????
#  EMAIL ? 3 option de provider
# ??????????????????????????????????????????????????????????????

# ?? OPTION 1 : Mailtrap (dev/test) ????????????????????????????
# Créez un compte sur https://mailtrap.io ? Inboxes ? SMTP Settings
#spring.mail.host=sandbox.smtp.mailtrap.io
#spring.mail.port=2525
#spring.mail.username=912681ceb0ac67
#spring.mail.password=416814ede846a4
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true

# ?? OPTION 2 : Gmail SMTP ?????????????????????????????????????
# Activez "Mots de passe d'application" dans votre compte Google
# https://myaccount.google.com/apppasswords
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ayetteboubaya@gmail.com
spring.mail.password=vobsmxahkcobngbu
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# accessToken  : 15 minutes
app.jwt.expiration-ms=900000

# refreshToken : 7 jours
app.jwt.refresh-expiration-ms=604800000


# ?? OPTION 3 : SendGrid ???????????????????????????????????????
# https://app.sendgrid.com ? Settings ? API Keys
#spring.mail.host=smtp.sendgrid.net
#spring.mail.port=587
#spring.mail.username=apikey
#spring.mail.password=VOTRE_SENDGRID_API_KEY
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true

# Swagger UI ? http://localhost:8081/swagger-ui.html
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs
server.port=8081
# Tri des endpoints par méthode HTTP dans l'UI
springdoc.swagger-ui.operationsSorter=method

# Affiche les schémas des modèles dépliés par défaut
springdoc.swagger-ui.defaultModelsExpandDepth=1

# Désactive Swagger en production (optionnel ? commentez pour le laisser actif)
# springdoc.swagger-ui.enabled=false
# springdoc.api-docs.enabled=false